name: Duplicate code

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Check for duplicate files
        run: |
         if ./duplicate.sh; then
            echo ::set-env name=HAVE_FILE::true
         fi
      - run: echo "I have file!"
        if:  env.HAVE_FILE == 'true'
