name: Duplicate code

on: push

jobs:
  run:
    name: Check for duplicate files
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: running script
        run: .github/duplicate.sh
