name: Duplicate code

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Check for duplicate files
        run : ./duplicate.sh
        id: duplicate
        shell: bash
      - name: Get the filenames
        run: echo "There seems to have a doublon. ${{ steps.duplicate.outputs.duplicate_filename }}"
        id : get-name
        if:  steps.duplicate.outputs.duplicate_filename != '0'
      - name: Check on failures
        if: job.steps.get-name.status == success()
        run: exit 1
