# This workflow will build a Java project with Ant
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-ant

name: Test French editorial

on:
  push:
    paths:
    - 'texts/xml/**'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
       - uses: actions/checkout@v2
       - name: Set up JDK 1.8
         uses: actions/setup-java@v1
         with:
           java-version: 1.8
       - name: Build with Ant
         run: ant -buildfile build1.xml
       - uses: actions/upload-artifact@v2
         with:
           name: output
           path: texts/edition-translation
         
