name: Test display 2 (bash)

on:
  push

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Display the path
        run: echo build2
        shell: bash
      - uses: actions/upload-artifact@v2
